#!/bin/bash

# Read from the USB device to stdout.
# Exit with ctl+A then ctl+\

# This has only been tested on MacOS.

baud_rate=9600
mount_name='tty.usbmodem1101'

sleep 1 \
&& screen /dev/"$mount_name" $baud_rate;
